/* AUTO-GENERATED by scripts/generate-seo-catalog.mjs — do not edit by hand */
import type { SeoCatalogRow } from './seoTopicTemplates'

export const SEO_CATALOG: SeoCatalogRow[] = [
  {
    "slug": "kak-zabindit-pokupku-oruzhiya",
    "group": "how-to",
    "topic": "buy",
    "kw": "как забиндить покупку оружия CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "kak-sdelat-bay-bindy",
    "group": "how-to",
    "topic": "buy",
    "kw": "как сделать бай бинды CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "bay-bindy-ks2",
    "group": "binds",
    "topic": "buy",
    "kw": "бай бинды кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "bay-bindy-ksgo2",
    "group": "binds",
    "topic": "buy",
    "kw": "бай бинды ксго2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "buy-binds-cs2",
    "group": "binds",
    "topic": "buy",
    "kw": "buy binds CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "kak-zabindit-jumpthrow",
    "group": "how-to",
    "topic": "jumpthrow",
    "kw": "как забиндить jumpthrow CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "jumpthrow-ks2",
    "group": "binds",
    "topic": "jumpthrow",
    "kw": "jumpthrow кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "dzhamptrou-bind",
    "group": "binds",
    "topic": "jumpthrow",
    "kw": "джамптроу бинд CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "bindy-granat-ks2",
    "group": "binds",
    "topic": "grenade",
    "kw": "бинды гранат кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "bind-na-smok",
    "group": "how-to",
    "topic": "grenade",
    "kw": "бинд на смок CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "bind-na-fleshku",
    "group": "how-to",
    "topic": "grenade",
    "kw": "бинд на флешку CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "kak-nastroit-pritsel",
    "group": "how-to",
    "topic": "crosshair",
    "kw": "как настроить прицел CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "pritsel-ks2",
    "group": "binds",
    "topic": "crosshair",
    "kw": "прицел кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "crosshair-cs2",
    "group": "binds",
    "topic": "crosshair",
    "kw": "crosshair CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "radar-ks2",
    "group": "binds",
    "topic": "radar",
    "kw": "радар кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "kak-nastroit-radar",
    "group": "how-to",
    "topic": "radar",
    "kw": "как настроить радар CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "viewmodel-cs2",
    "group": "binds",
    "topic": "viewmodel",
    "kw": "viewmodel CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "fov-cs2",
    "group": "binds",
    "topic": "viewmodel",
    "kw": "FOV CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "unbindall-cs2",
    "group": "binds",
    "topic": "unbind",
    "kw": "unbindall CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "kak-sbrosit-bindy",
    "group": "how-to",
    "topic": "unbind",
    "kw": "как сбросить бинды CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "nastrojki-fps-ks2",
    "group": "binds",
    "topic": "fps",
    "kw": "настройки FPS кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "kak-povysit-fps-ks2",
    "group": "how-to",
    "topic": "fps",
    "kw": "как повысить FPS кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "nastrojki-zvuka-ks2",
    "group": "binds",
    "topic": "sound",
    "kw": "настройки звука кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "autoexec-cs2",
    "group": "guides",
    "topic": "autoexec",
    "kw": "autoexec CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "konfig-ks2",
    "group": "guides",
    "topic": "config",
    "kw": "конфиг кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "bindy-ks2",
    "group": "guides",
    "topic": "general",
    "kw": "бинды кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "bindy-ksgo2",
    "group": "guides",
    "topic": "general",
    "kw": "бинды ксго2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "luchshie-bindy-ks2",
    "group": "guides",
    "topic": "general",
    "kw": "лучшие бинды кс2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "generator-bindov-cs2",
    "group": "guides",
    "topic": "general",
    "kw": "генератор биндов CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "kak-vstavit-bindy-v-konsol",
    "group": "how-to",
    "topic": "console",
    "kw": "как вставить бинды в консоль CS2",
    "extra": [
      "ксго2",
      "CS2"
    ]
  },
  {
    "slug": "gayd-dust2-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Dust 2 CS2",
    "extra": [
      "гайд даст2 CS2",
      "карта Dust 2 CS2"
    ]
  },
  {
    "slug": "gayd-dust2-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Dust 2 кс2",
    "extra": [
      "гайд даст2 кс2",
      "карта Dust 2 кс2"
    ]
  },
  {
    "slug": "gayd-dust2-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Dust 2 ксго2",
    "extra": [
      "гайд даст2 ксго2",
      "карта Dust 2 ксго2"
    ]
  },
  {
    "slug": "gayd-dust2-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Dust 2 Counter-Strike 2",
    "extra": [
      "гайд даст2 Counter-Strike 2",
      "карта Dust 2 Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-dust2-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Dust 2 CS2",
    "extra": [
      "тактика даст2 CS2",
      "карта Dust 2 CS2"
    ]
  },
  {
    "slug": "taktika-dust2-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Dust 2 кс2",
    "extra": [
      "тактика даст2 кс2",
      "карта Dust 2 кс2"
    ]
  },
  {
    "slug": "taktika-dust2-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Dust 2 ксго2",
    "extra": [
      "тактика даст2 ксго2",
      "карта Dust 2 ксго2"
    ]
  },
  {
    "slug": "taktika-dust2-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Dust 2 Counter-Strike 2",
    "extra": [
      "тактика даст2 Counter-Strike 2",
      "карта Dust 2 Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-dust2-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Dust 2 CS2",
    "extra": [
      "как играть даст2 CS2",
      "карта Dust 2 CS2"
    ]
  },
  {
    "slug": "kak-igrat-dust2-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Dust 2 кс2",
    "extra": [
      "как играть даст2 кс2",
      "карта Dust 2 кс2"
    ]
  },
  {
    "slug": "kak-igrat-dust2-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Dust 2 ксго2",
    "extra": [
      "как играть даст2 ксго2",
      "карта Dust 2 ксго2"
    ]
  },
  {
    "slug": "kak-igrat-dust2-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Dust 2 Counter-Strike 2",
    "extra": [
      "как играть даст2 Counter-Strike 2",
      "карта Dust 2 Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-dust2-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Dust 2 CS2",
    "extra": [
      "смоки даст2 CS2",
      "карта Dust 2 CS2"
    ]
  },
  {
    "slug": "smoki-dust2-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Dust 2 кс2",
    "extra": [
      "смоки даст2 кс2",
      "карта Dust 2 кс2"
    ]
  },
  {
    "slug": "smoki-dust2-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Dust 2 ксго2",
    "extra": [
      "смоки даст2 ксго2",
      "карта Dust 2 ксго2"
    ]
  },
  {
    "slug": "smoki-dust2-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Dust 2 Counter-Strike 2",
    "extra": [
      "смоки даст2 Counter-Strike 2",
      "карта Dust 2 Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-dust2-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Dust 2 CS2",
    "extra": [
      "позиции даст2 CS2",
      "карта Dust 2 CS2"
    ]
  },
  {
    "slug": "pozicii-dust2-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Dust 2 кс2",
    "extra": [
      "позиции даст2 кс2",
      "карта Dust 2 кс2"
    ]
  },
  {
    "slug": "pozicii-dust2-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Dust 2 ксго2",
    "extra": [
      "позиции даст2 ксго2",
      "карта Dust 2 ксго2"
    ]
  },
  {
    "slug": "pozicii-dust2-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Dust 2 Counter-Strike 2",
    "extra": [
      "позиции даст2 Counter-Strike 2",
      "карта Dust 2 Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-dust2-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Dust 2 CS2",
    "extra": [
      "коллауты даст2 CS2",
      "карта Dust 2 CS2"
    ]
  },
  {
    "slug": "callouty-dust2-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Dust 2 кс2",
    "extra": [
      "коллауты даст2 кс2",
      "карта Dust 2 кс2"
    ]
  },
  {
    "slug": "callouty-dust2-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Dust 2 ксго2",
    "extra": [
      "коллауты даст2 ксго2",
      "карта Dust 2 ксго2"
    ]
  },
  {
    "slug": "callouty-dust2-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Dust 2 Counter-Strike 2",
    "extra": [
      "коллауты даст2 Counter-Strike 2",
      "карта Dust 2 Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-dust2-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Dust 2 CS2",
    "extra": [
      "советы даст2 CS2",
      "карта Dust 2 CS2"
    ]
  },
  {
    "slug": "tips-dust2-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Dust 2 кс2",
    "extra": [
      "советы даст2 кс2",
      "карта Dust 2 кс2"
    ]
  },
  {
    "slug": "tips-dust2-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Dust 2 ксго2",
    "extra": [
      "советы даст2 ксго2",
      "карта Dust 2 ксго2"
    ]
  },
  {
    "slug": "tips-dust2-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Dust 2 Counter-Strike 2",
    "extra": [
      "советы даст2 Counter-Strike 2",
      "карта Dust 2 Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-dust2-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Dust 2 CS2",
    "extra": [
      "для новичков даст2 CS2",
      "карта Dust 2 CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-dust2-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Dust 2 кс2",
    "extra": [
      "для новичков даст2 кс2",
      "карта Dust 2 кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-dust2-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Dust 2 ксго2",
    "extra": [
      "для новичков даст2 ксго2",
      "карта Dust 2 ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-dust2-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Dust 2 Counter-Strike 2",
    "extra": [
      "для новичков даст2 Counter-Strike 2",
      "карта Dust 2 Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-mirage-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Mirage CS2",
    "extra": [
      "гайд мираж CS2",
      "карта Mirage CS2"
    ]
  },
  {
    "slug": "gayd-mirage-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Mirage кс2",
    "extra": [
      "гайд мираж кс2",
      "карта Mirage кс2"
    ]
  },
  {
    "slug": "gayd-mirage-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Mirage ксго2",
    "extra": [
      "гайд мираж ксго2",
      "карта Mirage ксго2"
    ]
  },
  {
    "slug": "gayd-mirage-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Mirage Counter-Strike 2",
    "extra": [
      "гайд мираж Counter-Strike 2",
      "карта Mirage Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-mirage-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Mirage CS2",
    "extra": [
      "тактика мираж CS2",
      "карта Mirage CS2"
    ]
  },
  {
    "slug": "taktika-mirage-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Mirage кс2",
    "extra": [
      "тактика мираж кс2",
      "карта Mirage кс2"
    ]
  },
  {
    "slug": "taktika-mirage-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Mirage ксго2",
    "extra": [
      "тактика мираж ксго2",
      "карта Mirage ксго2"
    ]
  },
  {
    "slug": "taktika-mirage-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Mirage Counter-Strike 2",
    "extra": [
      "тактика мираж Counter-Strike 2",
      "карта Mirage Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-mirage-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Mirage CS2",
    "extra": [
      "как играть мираж CS2",
      "карта Mirage CS2"
    ]
  },
  {
    "slug": "kak-igrat-mirage-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Mirage кс2",
    "extra": [
      "как играть мираж кс2",
      "карта Mirage кс2"
    ]
  },
  {
    "slug": "kak-igrat-mirage-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Mirage ксго2",
    "extra": [
      "как играть мираж ксго2",
      "карта Mirage ксго2"
    ]
  },
  {
    "slug": "kak-igrat-mirage-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Mirage Counter-Strike 2",
    "extra": [
      "как играть мираж Counter-Strike 2",
      "карта Mirage Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-mirage-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Mirage CS2",
    "extra": [
      "смоки мираж CS2",
      "карта Mirage CS2"
    ]
  },
  {
    "slug": "smoki-mirage-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Mirage кс2",
    "extra": [
      "смоки мираж кс2",
      "карта Mirage кс2"
    ]
  },
  {
    "slug": "smoki-mirage-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Mirage ксго2",
    "extra": [
      "смоки мираж ксго2",
      "карта Mirage ксго2"
    ]
  },
  {
    "slug": "smoki-mirage-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Mirage Counter-Strike 2",
    "extra": [
      "смоки мираж Counter-Strike 2",
      "карта Mirage Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-mirage-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Mirage CS2",
    "extra": [
      "позиции мираж CS2",
      "карта Mirage CS2"
    ]
  },
  {
    "slug": "pozicii-mirage-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Mirage кс2",
    "extra": [
      "позиции мираж кс2",
      "карта Mirage кс2"
    ]
  },
  {
    "slug": "pozicii-mirage-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Mirage ксго2",
    "extra": [
      "позиции мираж ксго2",
      "карта Mirage ксго2"
    ]
  },
  {
    "slug": "pozicii-mirage-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Mirage Counter-Strike 2",
    "extra": [
      "позиции мираж Counter-Strike 2",
      "карта Mirage Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-mirage-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Mirage CS2",
    "extra": [
      "коллауты мираж CS2",
      "карта Mirage CS2"
    ]
  },
  {
    "slug": "callouty-mirage-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Mirage кс2",
    "extra": [
      "коллауты мираж кс2",
      "карта Mirage кс2"
    ]
  },
  {
    "slug": "callouty-mirage-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Mirage ксго2",
    "extra": [
      "коллауты мираж ксго2",
      "карта Mirage ксго2"
    ]
  },
  {
    "slug": "callouty-mirage-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Mirage Counter-Strike 2",
    "extra": [
      "коллауты мираж Counter-Strike 2",
      "карта Mirage Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-mirage-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Mirage CS2",
    "extra": [
      "советы мираж CS2",
      "карта Mirage CS2"
    ]
  },
  {
    "slug": "tips-mirage-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Mirage кс2",
    "extra": [
      "советы мираж кс2",
      "карта Mirage кс2"
    ]
  },
  {
    "slug": "tips-mirage-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Mirage ксго2",
    "extra": [
      "советы мираж ксго2",
      "карта Mirage ксго2"
    ]
  },
  {
    "slug": "tips-mirage-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Mirage Counter-Strike 2",
    "extra": [
      "советы мираж Counter-Strike 2",
      "карта Mirage Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-mirage-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Mirage CS2",
    "extra": [
      "для новичков мираж CS2",
      "карта Mirage CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-mirage-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Mirage кс2",
    "extra": [
      "для новичков мираж кс2",
      "карта Mirage кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-mirage-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Mirage ксго2",
    "extra": [
      "для новичков мираж ксго2",
      "карта Mirage ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-mirage-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Mirage Counter-Strike 2",
    "extra": [
      "для новичков мираж Counter-Strike 2",
      "карта Mirage Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-inferno-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Inferno CS2",
    "extra": [
      "гайд инферно CS2",
      "карта Inferno CS2"
    ]
  },
  {
    "slug": "gayd-inferno-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Inferno кс2",
    "extra": [
      "гайд инферно кс2",
      "карта Inferno кс2"
    ]
  },
  {
    "slug": "gayd-inferno-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Inferno ксго2",
    "extra": [
      "гайд инферно ксго2",
      "карта Inferno ксго2"
    ]
  },
  {
    "slug": "gayd-inferno-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Inferno Counter-Strike 2",
    "extra": [
      "гайд инферно Counter-Strike 2",
      "карта Inferno Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-inferno-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Inferno CS2",
    "extra": [
      "тактика инферно CS2",
      "карта Inferno CS2"
    ]
  },
  {
    "slug": "taktika-inferno-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Inferno кс2",
    "extra": [
      "тактика инферно кс2",
      "карта Inferno кс2"
    ]
  },
  {
    "slug": "taktika-inferno-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Inferno ксго2",
    "extra": [
      "тактика инферно ксго2",
      "карта Inferno ксго2"
    ]
  },
  {
    "slug": "taktika-inferno-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Inferno Counter-Strike 2",
    "extra": [
      "тактика инферно Counter-Strike 2",
      "карта Inferno Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-inferno-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Inferno CS2",
    "extra": [
      "как играть инферно CS2",
      "карта Inferno CS2"
    ]
  },
  {
    "slug": "kak-igrat-inferno-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Inferno кс2",
    "extra": [
      "как играть инферно кс2",
      "карта Inferno кс2"
    ]
  },
  {
    "slug": "kak-igrat-inferno-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Inferno ксго2",
    "extra": [
      "как играть инферно ксго2",
      "карта Inferno ксго2"
    ]
  },
  {
    "slug": "kak-igrat-inferno-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Inferno Counter-Strike 2",
    "extra": [
      "как играть инферно Counter-Strike 2",
      "карта Inferno Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-inferno-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Inferno CS2",
    "extra": [
      "смоки инферно CS2",
      "карта Inferno CS2"
    ]
  },
  {
    "slug": "smoki-inferno-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Inferno кс2",
    "extra": [
      "смоки инферно кс2",
      "карта Inferno кс2"
    ]
  },
  {
    "slug": "smoki-inferno-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Inferno ксго2",
    "extra": [
      "смоки инферно ксго2",
      "карта Inferno ксго2"
    ]
  },
  {
    "slug": "smoki-inferno-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Inferno Counter-Strike 2",
    "extra": [
      "смоки инферно Counter-Strike 2",
      "карта Inferno Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-inferno-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Inferno CS2",
    "extra": [
      "позиции инферно CS2",
      "карта Inferno CS2"
    ]
  },
  {
    "slug": "pozicii-inferno-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Inferno кс2",
    "extra": [
      "позиции инферно кс2",
      "карта Inferno кс2"
    ]
  },
  {
    "slug": "pozicii-inferno-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Inferno ксго2",
    "extra": [
      "позиции инферно ксго2",
      "карта Inferno ксго2"
    ]
  },
  {
    "slug": "pozicii-inferno-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Inferno Counter-Strike 2",
    "extra": [
      "позиции инферно Counter-Strike 2",
      "карта Inferno Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-inferno-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Inferno CS2",
    "extra": [
      "коллауты инферно CS2",
      "карта Inferno CS2"
    ]
  },
  {
    "slug": "callouty-inferno-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Inferno кс2",
    "extra": [
      "коллауты инферно кс2",
      "карта Inferno кс2"
    ]
  },
  {
    "slug": "callouty-inferno-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Inferno ксго2",
    "extra": [
      "коллауты инферно ксго2",
      "карта Inferno ксго2"
    ]
  },
  {
    "slug": "callouty-inferno-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Inferno Counter-Strike 2",
    "extra": [
      "коллауты инферно Counter-Strike 2",
      "карта Inferno Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-inferno-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Inferno CS2",
    "extra": [
      "советы инферно CS2",
      "карта Inferno CS2"
    ]
  },
  {
    "slug": "tips-inferno-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Inferno кс2",
    "extra": [
      "советы инферно кс2",
      "карта Inferno кс2"
    ]
  },
  {
    "slug": "tips-inferno-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Inferno ксго2",
    "extra": [
      "советы инферно ксго2",
      "карта Inferno ксго2"
    ]
  },
  {
    "slug": "tips-inferno-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Inferno Counter-Strike 2",
    "extra": [
      "советы инферно Counter-Strike 2",
      "карта Inferno Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-inferno-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Inferno CS2",
    "extra": [
      "для новичков инферно CS2",
      "карта Inferno CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-inferno-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Inferno кс2",
    "extra": [
      "для новичков инферно кс2",
      "карта Inferno кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-inferno-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Inferno ксго2",
    "extra": [
      "для новичков инферно ксго2",
      "карта Inferno ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-inferno-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Inferno Counter-Strike 2",
    "extra": [
      "для новичков инферно Counter-Strike 2",
      "карта Inferno Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-nuke-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Nuke CS2",
    "extra": [
      "гайд нюк CS2",
      "карта Nuke CS2"
    ]
  },
  {
    "slug": "gayd-nuke-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Nuke кс2",
    "extra": [
      "гайд нюк кс2",
      "карта Nuke кс2"
    ]
  },
  {
    "slug": "gayd-nuke-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Nuke ксго2",
    "extra": [
      "гайд нюк ксго2",
      "карта Nuke ксго2"
    ]
  },
  {
    "slug": "gayd-nuke-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Nuke Counter-Strike 2",
    "extra": [
      "гайд нюк Counter-Strike 2",
      "карта Nuke Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-nuke-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Nuke CS2",
    "extra": [
      "тактика нюк CS2",
      "карта Nuke CS2"
    ]
  },
  {
    "slug": "taktika-nuke-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Nuke кс2",
    "extra": [
      "тактика нюк кс2",
      "карта Nuke кс2"
    ]
  },
  {
    "slug": "taktika-nuke-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Nuke ксго2",
    "extra": [
      "тактика нюк ксго2",
      "карта Nuke ксго2"
    ]
  },
  {
    "slug": "taktika-nuke-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Nuke Counter-Strike 2",
    "extra": [
      "тактика нюк Counter-Strike 2",
      "карта Nuke Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-nuke-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Nuke CS2",
    "extra": [
      "как играть нюк CS2",
      "карта Nuke CS2"
    ]
  },
  {
    "slug": "kak-igrat-nuke-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Nuke кс2",
    "extra": [
      "как играть нюк кс2",
      "карта Nuke кс2"
    ]
  },
  {
    "slug": "kak-igrat-nuke-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Nuke ксго2",
    "extra": [
      "как играть нюк ксго2",
      "карта Nuke ксго2"
    ]
  },
  {
    "slug": "kak-igrat-nuke-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Nuke Counter-Strike 2",
    "extra": [
      "как играть нюк Counter-Strike 2",
      "карта Nuke Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-nuke-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Nuke CS2",
    "extra": [
      "смоки нюк CS2",
      "карта Nuke CS2"
    ]
  },
  {
    "slug": "smoki-nuke-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Nuke кс2",
    "extra": [
      "смоки нюк кс2",
      "карта Nuke кс2"
    ]
  },
  {
    "slug": "smoki-nuke-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Nuke ксго2",
    "extra": [
      "смоки нюк ксго2",
      "карта Nuke ксго2"
    ]
  },
  {
    "slug": "smoki-nuke-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Nuke Counter-Strike 2",
    "extra": [
      "смоки нюк Counter-Strike 2",
      "карта Nuke Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-nuke-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Nuke CS2",
    "extra": [
      "позиции нюк CS2",
      "карта Nuke CS2"
    ]
  },
  {
    "slug": "pozicii-nuke-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Nuke кс2",
    "extra": [
      "позиции нюк кс2",
      "карта Nuke кс2"
    ]
  },
  {
    "slug": "pozicii-nuke-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Nuke ксго2",
    "extra": [
      "позиции нюк ксго2",
      "карта Nuke ксго2"
    ]
  },
  {
    "slug": "pozicii-nuke-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Nuke Counter-Strike 2",
    "extra": [
      "позиции нюк Counter-Strike 2",
      "карта Nuke Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-nuke-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Nuke CS2",
    "extra": [
      "коллауты нюк CS2",
      "карта Nuke CS2"
    ]
  },
  {
    "slug": "callouty-nuke-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Nuke кс2",
    "extra": [
      "коллауты нюк кс2",
      "карта Nuke кс2"
    ]
  },
  {
    "slug": "callouty-nuke-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Nuke ксго2",
    "extra": [
      "коллауты нюк ксго2",
      "карта Nuke ксго2"
    ]
  },
  {
    "slug": "callouty-nuke-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Nuke Counter-Strike 2",
    "extra": [
      "коллауты нюк Counter-Strike 2",
      "карта Nuke Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-nuke-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Nuke CS2",
    "extra": [
      "советы нюк CS2",
      "карта Nuke CS2"
    ]
  },
  {
    "slug": "tips-nuke-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Nuke кс2",
    "extra": [
      "советы нюк кс2",
      "карта Nuke кс2"
    ]
  },
  {
    "slug": "tips-nuke-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Nuke ксго2",
    "extra": [
      "советы нюк ксго2",
      "карта Nuke ксго2"
    ]
  },
  {
    "slug": "tips-nuke-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Nuke Counter-Strike 2",
    "extra": [
      "советы нюк Counter-Strike 2",
      "карта Nuke Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-nuke-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Nuke CS2",
    "extra": [
      "для новичков нюк CS2",
      "карта Nuke CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-nuke-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Nuke кс2",
    "extra": [
      "для новичков нюк кс2",
      "карта Nuke кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-nuke-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Nuke ксго2",
    "extra": [
      "для новичков нюк ксго2",
      "карта Nuke ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-nuke-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Nuke Counter-Strike 2",
    "extra": [
      "для новичков нюк Counter-Strike 2",
      "карта Nuke Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-ancient-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Ancient CS2",
    "extra": [
      "гайд эншент CS2",
      "карта Ancient CS2"
    ]
  },
  {
    "slug": "gayd-ancient-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Ancient кс2",
    "extra": [
      "гайд эншент кс2",
      "карта Ancient кс2"
    ]
  },
  {
    "slug": "gayd-ancient-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Ancient ксго2",
    "extra": [
      "гайд эншент ксго2",
      "карта Ancient ксго2"
    ]
  },
  {
    "slug": "gayd-ancient-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Ancient Counter-Strike 2",
    "extra": [
      "гайд эншент Counter-Strike 2",
      "карта Ancient Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-ancient-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Ancient CS2",
    "extra": [
      "тактика эншент CS2",
      "карта Ancient CS2"
    ]
  },
  {
    "slug": "taktika-ancient-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Ancient кс2",
    "extra": [
      "тактика эншент кс2",
      "карта Ancient кс2"
    ]
  },
  {
    "slug": "taktika-ancient-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Ancient ксго2",
    "extra": [
      "тактика эншент ксго2",
      "карта Ancient ксго2"
    ]
  },
  {
    "slug": "taktika-ancient-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Ancient Counter-Strike 2",
    "extra": [
      "тактика эншент Counter-Strike 2",
      "карта Ancient Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-ancient-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Ancient CS2",
    "extra": [
      "как играть эншент CS2",
      "карта Ancient CS2"
    ]
  },
  {
    "slug": "kak-igrat-ancient-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Ancient кс2",
    "extra": [
      "как играть эншент кс2",
      "карта Ancient кс2"
    ]
  },
  {
    "slug": "kak-igrat-ancient-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Ancient ксго2",
    "extra": [
      "как играть эншент ксго2",
      "карта Ancient ксго2"
    ]
  },
  {
    "slug": "kak-igrat-ancient-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Ancient Counter-Strike 2",
    "extra": [
      "как играть эншент Counter-Strike 2",
      "карта Ancient Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-ancient-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Ancient CS2",
    "extra": [
      "смоки эншент CS2",
      "карта Ancient CS2"
    ]
  },
  {
    "slug": "smoki-ancient-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Ancient кс2",
    "extra": [
      "смоки эншент кс2",
      "карта Ancient кс2"
    ]
  },
  {
    "slug": "smoki-ancient-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Ancient ксго2",
    "extra": [
      "смоки эншент ксго2",
      "карта Ancient ксго2"
    ]
  },
  {
    "slug": "smoki-ancient-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Ancient Counter-Strike 2",
    "extra": [
      "смоки эншент Counter-Strike 2",
      "карта Ancient Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-ancient-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Ancient CS2",
    "extra": [
      "позиции эншент CS2",
      "карта Ancient CS2"
    ]
  },
  {
    "slug": "pozicii-ancient-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Ancient кс2",
    "extra": [
      "позиции эншент кс2",
      "карта Ancient кс2"
    ]
  },
  {
    "slug": "pozicii-ancient-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Ancient ксго2",
    "extra": [
      "позиции эншент ксго2",
      "карта Ancient ксго2"
    ]
  },
  {
    "slug": "pozicii-ancient-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Ancient Counter-Strike 2",
    "extra": [
      "позиции эншент Counter-Strike 2",
      "карта Ancient Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-ancient-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Ancient CS2",
    "extra": [
      "коллауты эншент CS2",
      "карта Ancient CS2"
    ]
  },
  {
    "slug": "callouty-ancient-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Ancient кс2",
    "extra": [
      "коллауты эншент кс2",
      "карта Ancient кс2"
    ]
  },
  {
    "slug": "callouty-ancient-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Ancient ксго2",
    "extra": [
      "коллауты эншент ксго2",
      "карта Ancient ксго2"
    ]
  },
  {
    "slug": "callouty-ancient-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Ancient Counter-Strike 2",
    "extra": [
      "коллауты эншент Counter-Strike 2",
      "карта Ancient Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-ancient-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Ancient CS2",
    "extra": [
      "советы эншент CS2",
      "карта Ancient CS2"
    ]
  },
  {
    "slug": "tips-ancient-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Ancient кс2",
    "extra": [
      "советы эншент кс2",
      "карта Ancient кс2"
    ]
  },
  {
    "slug": "tips-ancient-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Ancient ксго2",
    "extra": [
      "советы эншент ксго2",
      "карта Ancient ксго2"
    ]
  },
  {
    "slug": "tips-ancient-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Ancient Counter-Strike 2",
    "extra": [
      "советы эншент Counter-Strike 2",
      "карта Ancient Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-ancient-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Ancient CS2",
    "extra": [
      "для новичков эншент CS2",
      "карта Ancient CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-ancient-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Ancient кс2",
    "extra": [
      "для новичков эншент кс2",
      "карта Ancient кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-ancient-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Ancient ксго2",
    "extra": [
      "для новичков эншент ксго2",
      "карта Ancient ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-ancient-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Ancient Counter-Strike 2",
    "extra": [
      "для новичков эншент Counter-Strike 2",
      "карта Ancient Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-anubis-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Anubis CS2",
    "extra": [
      "гайд анубис CS2",
      "карта Anubis CS2"
    ]
  },
  {
    "slug": "gayd-anubis-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Anubis кс2",
    "extra": [
      "гайд анубис кс2",
      "карта Anubis кс2"
    ]
  },
  {
    "slug": "gayd-anubis-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Anubis ксго2",
    "extra": [
      "гайд анубис ксго2",
      "карта Anubis ксго2"
    ]
  },
  {
    "slug": "gayd-anubis-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Anubis Counter-Strike 2",
    "extra": [
      "гайд анубис Counter-Strike 2",
      "карта Anubis Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-anubis-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Anubis CS2",
    "extra": [
      "тактика анубис CS2",
      "карта Anubis CS2"
    ]
  },
  {
    "slug": "taktika-anubis-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Anubis кс2",
    "extra": [
      "тактика анубис кс2",
      "карта Anubis кс2"
    ]
  },
  {
    "slug": "taktika-anubis-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Anubis ксго2",
    "extra": [
      "тактика анубис ксго2",
      "карта Anubis ксго2"
    ]
  },
  {
    "slug": "taktika-anubis-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Anubis Counter-Strike 2",
    "extra": [
      "тактика анубис Counter-Strike 2",
      "карта Anubis Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-anubis-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Anubis CS2",
    "extra": [
      "как играть анубис CS2",
      "карта Anubis CS2"
    ]
  },
  {
    "slug": "kak-igrat-anubis-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Anubis кс2",
    "extra": [
      "как играть анубис кс2",
      "карта Anubis кс2"
    ]
  },
  {
    "slug": "kak-igrat-anubis-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Anubis ксго2",
    "extra": [
      "как играть анубис ксго2",
      "карта Anubis ксго2"
    ]
  },
  {
    "slug": "kak-igrat-anubis-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Anubis Counter-Strike 2",
    "extra": [
      "как играть анубис Counter-Strike 2",
      "карта Anubis Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-anubis-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Anubis CS2",
    "extra": [
      "смоки анубис CS2",
      "карта Anubis CS2"
    ]
  },
  {
    "slug": "smoki-anubis-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Anubis кс2",
    "extra": [
      "смоки анубис кс2",
      "карта Anubis кс2"
    ]
  },
  {
    "slug": "smoki-anubis-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Anubis ксго2",
    "extra": [
      "смоки анубис ксго2",
      "карта Anubis ксго2"
    ]
  },
  {
    "slug": "smoki-anubis-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Anubis Counter-Strike 2",
    "extra": [
      "смоки анубис Counter-Strike 2",
      "карта Anubis Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-anubis-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Anubis CS2",
    "extra": [
      "позиции анубис CS2",
      "карта Anubis CS2"
    ]
  },
  {
    "slug": "pozicii-anubis-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Anubis кс2",
    "extra": [
      "позиции анубис кс2",
      "карта Anubis кс2"
    ]
  },
  {
    "slug": "pozicii-anubis-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Anubis ксго2",
    "extra": [
      "позиции анубис ксго2",
      "карта Anubis ксго2"
    ]
  },
  {
    "slug": "pozicii-anubis-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Anubis Counter-Strike 2",
    "extra": [
      "позиции анубис Counter-Strike 2",
      "карта Anubis Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-anubis-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Anubis CS2",
    "extra": [
      "коллауты анубис CS2",
      "карта Anubis CS2"
    ]
  },
  {
    "slug": "callouty-anubis-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Anubis кс2",
    "extra": [
      "коллауты анубис кс2",
      "карта Anubis кс2"
    ]
  },
  {
    "slug": "callouty-anubis-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Anubis ксго2",
    "extra": [
      "коллауты анубис ксго2",
      "карта Anubis ксго2"
    ]
  },
  {
    "slug": "callouty-anubis-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Anubis Counter-Strike 2",
    "extra": [
      "коллауты анубис Counter-Strike 2",
      "карта Anubis Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-anubis-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Anubis CS2",
    "extra": [
      "советы анубис CS2",
      "карта Anubis CS2"
    ]
  },
  {
    "slug": "tips-anubis-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Anubis кс2",
    "extra": [
      "советы анубис кс2",
      "карта Anubis кс2"
    ]
  },
  {
    "slug": "tips-anubis-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Anubis ксго2",
    "extra": [
      "советы анубис ксго2",
      "карта Anubis ксго2"
    ]
  },
  {
    "slug": "tips-anubis-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Anubis Counter-Strike 2",
    "extra": [
      "советы анубис Counter-Strike 2",
      "карта Anubis Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-anubis-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Anubis CS2",
    "extra": [
      "для новичков анубис CS2",
      "карта Anubis CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-anubis-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Anubis кс2",
    "extra": [
      "для новичков анубис кс2",
      "карта Anubis кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-anubis-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Anubis ксго2",
    "extra": [
      "для новичков анубис ксго2",
      "карта Anubis ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-anubis-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Anubis Counter-Strike 2",
    "extra": [
      "для новичков анубис Counter-Strike 2",
      "карта Anubis Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-vertigo-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Vertigo CS2",
    "extra": [
      "гайд вертиго CS2",
      "карта Vertigo CS2"
    ]
  },
  {
    "slug": "gayd-vertigo-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Vertigo кс2",
    "extra": [
      "гайд вертиго кс2",
      "карта Vertigo кс2"
    ]
  },
  {
    "slug": "gayd-vertigo-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Vertigo ксго2",
    "extra": [
      "гайд вертиго ксго2",
      "карта Vertigo ксго2"
    ]
  },
  {
    "slug": "gayd-vertigo-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Vertigo Counter-Strike 2",
    "extra": [
      "гайд вертиго Counter-Strike 2",
      "карта Vertigo Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-vertigo-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Vertigo CS2",
    "extra": [
      "тактика вертиго CS2",
      "карта Vertigo CS2"
    ]
  },
  {
    "slug": "taktika-vertigo-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Vertigo кс2",
    "extra": [
      "тактика вертиго кс2",
      "карта Vertigo кс2"
    ]
  },
  {
    "slug": "taktika-vertigo-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Vertigo ксго2",
    "extra": [
      "тактика вертиго ксго2",
      "карта Vertigo ксго2"
    ]
  },
  {
    "slug": "taktika-vertigo-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Vertigo Counter-Strike 2",
    "extra": [
      "тактика вертиго Counter-Strike 2",
      "карта Vertigo Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-vertigo-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Vertigo CS2",
    "extra": [
      "как играть вертиго CS2",
      "карта Vertigo CS2"
    ]
  },
  {
    "slug": "kak-igrat-vertigo-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Vertigo кс2",
    "extra": [
      "как играть вертиго кс2",
      "карта Vertigo кс2"
    ]
  },
  {
    "slug": "kak-igrat-vertigo-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Vertigo ксго2",
    "extra": [
      "как играть вертиго ксго2",
      "карта Vertigo ксго2"
    ]
  },
  {
    "slug": "kak-igrat-vertigo-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Vertigo Counter-Strike 2",
    "extra": [
      "как играть вертиго Counter-Strike 2",
      "карта Vertigo Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-vertigo-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Vertigo CS2",
    "extra": [
      "смоки вертиго CS2",
      "карта Vertigo CS2"
    ]
  },
  {
    "slug": "smoki-vertigo-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Vertigo кс2",
    "extra": [
      "смоки вертиго кс2",
      "карта Vertigo кс2"
    ]
  },
  {
    "slug": "smoki-vertigo-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Vertigo ксго2",
    "extra": [
      "смоки вертиго ксго2",
      "карта Vertigo ксго2"
    ]
  },
  {
    "slug": "smoki-vertigo-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Vertigo Counter-Strike 2",
    "extra": [
      "смоки вертиго Counter-Strike 2",
      "карта Vertigo Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-vertigo-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Vertigo CS2",
    "extra": [
      "позиции вертиго CS2",
      "карта Vertigo CS2"
    ]
  },
  {
    "slug": "pozicii-vertigo-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Vertigo кс2",
    "extra": [
      "позиции вертиго кс2",
      "карта Vertigo кс2"
    ]
  },
  {
    "slug": "pozicii-vertigo-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Vertigo ксго2",
    "extra": [
      "позиции вертиго ксго2",
      "карта Vertigo ксго2"
    ]
  },
  {
    "slug": "pozicii-vertigo-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Vertigo Counter-Strike 2",
    "extra": [
      "позиции вертиго Counter-Strike 2",
      "карта Vertigo Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-vertigo-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Vertigo CS2",
    "extra": [
      "коллауты вертиго CS2",
      "карта Vertigo CS2"
    ]
  },
  {
    "slug": "callouty-vertigo-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Vertigo кс2",
    "extra": [
      "коллауты вертиго кс2",
      "карта Vertigo кс2"
    ]
  },
  {
    "slug": "callouty-vertigo-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Vertigo ксго2",
    "extra": [
      "коллауты вертиго ксго2",
      "карта Vertigo ксго2"
    ]
  },
  {
    "slug": "callouty-vertigo-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Vertigo Counter-Strike 2",
    "extra": [
      "коллауты вертиго Counter-Strike 2",
      "карта Vertigo Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-vertigo-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Vertigo CS2",
    "extra": [
      "советы вертиго CS2",
      "карта Vertigo CS2"
    ]
  },
  {
    "slug": "tips-vertigo-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Vertigo кс2",
    "extra": [
      "советы вертиго кс2",
      "карта Vertigo кс2"
    ]
  },
  {
    "slug": "tips-vertigo-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Vertigo ксго2",
    "extra": [
      "советы вертиго ксго2",
      "карта Vertigo ксго2"
    ]
  },
  {
    "slug": "tips-vertigo-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Vertigo Counter-Strike 2",
    "extra": [
      "советы вертиго Counter-Strike 2",
      "карта Vertigo Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-vertigo-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Vertigo CS2",
    "extra": [
      "для новичков вертиго CS2",
      "карта Vertigo CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-vertigo-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Vertigo кс2",
    "extra": [
      "для новичков вертиго кс2",
      "карта Vertigo кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-vertigo-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Vertigo ксго2",
    "extra": [
      "для новичков вертиго ксго2",
      "карта Vertigo ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-vertigo-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Vertigo Counter-Strike 2",
    "extra": [
      "для новичков вертиго Counter-Strike 2",
      "карта Vertigo Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-overpass-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Overpass CS2",
    "extra": [
      "гайд оверпасс CS2",
      "карта Overpass CS2"
    ]
  },
  {
    "slug": "gayd-overpass-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Overpass кс2",
    "extra": [
      "гайд оверпасс кс2",
      "карта Overpass кс2"
    ]
  },
  {
    "slug": "gayd-overpass-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Overpass ксго2",
    "extra": [
      "гайд оверпасс ксго2",
      "карта Overpass ксго2"
    ]
  },
  {
    "slug": "gayd-overpass-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Overpass Counter-Strike 2",
    "extra": [
      "гайд оверпасс Counter-Strike 2",
      "карта Overpass Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-overpass-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Overpass CS2",
    "extra": [
      "тактика оверпасс CS2",
      "карта Overpass CS2"
    ]
  },
  {
    "slug": "taktika-overpass-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Overpass кс2",
    "extra": [
      "тактика оверпасс кс2",
      "карта Overpass кс2"
    ]
  },
  {
    "slug": "taktika-overpass-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Overpass ксго2",
    "extra": [
      "тактика оверпасс ксго2",
      "карта Overpass ксго2"
    ]
  },
  {
    "slug": "taktika-overpass-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Overpass Counter-Strike 2",
    "extra": [
      "тактика оверпасс Counter-Strike 2",
      "карта Overpass Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-overpass-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Overpass CS2",
    "extra": [
      "как играть оверпасс CS2",
      "карта Overpass CS2"
    ]
  },
  {
    "slug": "kak-igrat-overpass-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Overpass кс2",
    "extra": [
      "как играть оверпасс кс2",
      "карта Overpass кс2"
    ]
  },
  {
    "slug": "kak-igrat-overpass-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Overpass ксго2",
    "extra": [
      "как играть оверпасс ксго2",
      "карта Overpass ксго2"
    ]
  },
  {
    "slug": "kak-igrat-overpass-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Overpass Counter-Strike 2",
    "extra": [
      "как играть оверпасс Counter-Strike 2",
      "карта Overpass Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-overpass-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Overpass CS2",
    "extra": [
      "смоки оверпасс CS2",
      "карта Overpass CS2"
    ]
  },
  {
    "slug": "smoki-overpass-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Overpass кс2",
    "extra": [
      "смоки оверпасс кс2",
      "карта Overpass кс2"
    ]
  },
  {
    "slug": "smoki-overpass-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Overpass ксго2",
    "extra": [
      "смоки оверпасс ксго2",
      "карта Overpass ксго2"
    ]
  },
  {
    "slug": "smoki-overpass-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Overpass Counter-Strike 2",
    "extra": [
      "смоки оверпасс Counter-Strike 2",
      "карта Overpass Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-overpass-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Overpass CS2",
    "extra": [
      "позиции оверпасс CS2",
      "карта Overpass CS2"
    ]
  },
  {
    "slug": "pozicii-overpass-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Overpass кс2",
    "extra": [
      "позиции оверпасс кс2",
      "карта Overpass кс2"
    ]
  },
  {
    "slug": "pozicii-overpass-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Overpass ксго2",
    "extra": [
      "позиции оверпасс ксго2",
      "карта Overpass ксго2"
    ]
  },
  {
    "slug": "pozicii-overpass-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Overpass Counter-Strike 2",
    "extra": [
      "позиции оверпасс Counter-Strike 2",
      "карта Overpass Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-overpass-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Overpass CS2",
    "extra": [
      "коллауты оверпасс CS2",
      "карта Overpass CS2"
    ]
  },
  {
    "slug": "callouty-overpass-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Overpass кс2",
    "extra": [
      "коллауты оверпасс кс2",
      "карта Overpass кс2"
    ]
  },
  {
    "slug": "callouty-overpass-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Overpass ксго2",
    "extra": [
      "коллауты оверпасс ксго2",
      "карта Overpass ксго2"
    ]
  },
  {
    "slug": "callouty-overpass-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Overpass Counter-Strike 2",
    "extra": [
      "коллауты оверпасс Counter-Strike 2",
      "карта Overpass Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-overpass-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Overpass CS2",
    "extra": [
      "советы оверпасс CS2",
      "карта Overpass CS2"
    ]
  },
  {
    "slug": "tips-overpass-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Overpass кс2",
    "extra": [
      "советы оверпасс кс2",
      "карта Overpass кс2"
    ]
  },
  {
    "slug": "tips-overpass-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Overpass ксго2",
    "extra": [
      "советы оверпасс ксго2",
      "карта Overpass ксго2"
    ]
  },
  {
    "slug": "tips-overpass-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Overpass Counter-Strike 2",
    "extra": [
      "советы оверпасс Counter-Strike 2",
      "карта Overpass Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-overpass-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Overpass CS2",
    "extra": [
      "для новичков оверпасс CS2",
      "карта Overpass CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-overpass-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Overpass кс2",
    "extra": [
      "для новичков оверпасс кс2",
      "карта Overpass кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-overpass-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Overpass ксго2",
    "extra": [
      "для новичков оверпасс ксго2",
      "карта Overpass ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-overpass-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Overpass Counter-Strike 2",
    "extra": [
      "для новичков оверпасс Counter-Strike 2",
      "карта Overpass Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-train-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Train CS2",
    "extra": [
      "гайд трейн CS2",
      "карта Train CS2"
    ]
  },
  {
    "slug": "gayd-train-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Train кс2",
    "extra": [
      "гайд трейн кс2",
      "карта Train кс2"
    ]
  },
  {
    "slug": "gayd-train-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Train ксго2",
    "extra": [
      "гайд трейн ксго2",
      "карта Train ксго2"
    ]
  },
  {
    "slug": "gayd-train-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Train Counter-Strike 2",
    "extra": [
      "гайд трейн Counter-Strike 2",
      "карта Train Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-train-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Train CS2",
    "extra": [
      "тактика трейн CS2",
      "карта Train CS2"
    ]
  },
  {
    "slug": "taktika-train-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Train кс2",
    "extra": [
      "тактика трейн кс2",
      "карта Train кс2"
    ]
  },
  {
    "slug": "taktika-train-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Train ксго2",
    "extra": [
      "тактика трейн ксго2",
      "карта Train ксго2"
    ]
  },
  {
    "slug": "taktika-train-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Train Counter-Strike 2",
    "extra": [
      "тактика трейн Counter-Strike 2",
      "карта Train Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-train-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Train CS2",
    "extra": [
      "как играть трейн CS2",
      "карта Train CS2"
    ]
  },
  {
    "slug": "kak-igrat-train-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Train кс2",
    "extra": [
      "как играть трейн кс2",
      "карта Train кс2"
    ]
  },
  {
    "slug": "kak-igrat-train-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Train ксго2",
    "extra": [
      "как играть трейн ксго2",
      "карта Train ксго2"
    ]
  },
  {
    "slug": "kak-igrat-train-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Train Counter-Strike 2",
    "extra": [
      "как играть трейн Counter-Strike 2",
      "карта Train Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-train-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Train CS2",
    "extra": [
      "смоки трейн CS2",
      "карта Train CS2"
    ]
  },
  {
    "slug": "smoki-train-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Train кс2",
    "extra": [
      "смоки трейн кс2",
      "карта Train кс2"
    ]
  },
  {
    "slug": "smoki-train-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Train ксго2",
    "extra": [
      "смоки трейн ксго2",
      "карта Train ксго2"
    ]
  },
  {
    "slug": "smoki-train-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Train Counter-Strike 2",
    "extra": [
      "смоки трейн Counter-Strike 2",
      "карта Train Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-train-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Train CS2",
    "extra": [
      "позиции трейн CS2",
      "карта Train CS2"
    ]
  },
  {
    "slug": "pozicii-train-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Train кс2",
    "extra": [
      "позиции трейн кс2",
      "карта Train кс2"
    ]
  },
  {
    "slug": "pozicii-train-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Train ксго2",
    "extra": [
      "позиции трейн ксго2",
      "карта Train ксго2"
    ]
  },
  {
    "slug": "pozicii-train-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Train Counter-Strike 2",
    "extra": [
      "позиции трейн Counter-Strike 2",
      "карта Train Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-train-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Train CS2",
    "extra": [
      "коллауты трейн CS2",
      "карта Train CS2"
    ]
  },
  {
    "slug": "callouty-train-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Train кс2",
    "extra": [
      "коллауты трейн кс2",
      "карта Train кс2"
    ]
  },
  {
    "slug": "callouty-train-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Train ксго2",
    "extra": [
      "коллауты трейн ксго2",
      "карта Train ксго2"
    ]
  },
  {
    "slug": "callouty-train-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Train Counter-Strike 2",
    "extra": [
      "коллауты трейн Counter-Strike 2",
      "карта Train Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-train-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Train CS2",
    "extra": [
      "советы трейн CS2",
      "карта Train CS2"
    ]
  },
  {
    "slug": "tips-train-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Train кс2",
    "extra": [
      "советы трейн кс2",
      "карта Train кс2"
    ]
  },
  {
    "slug": "tips-train-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Train ксго2",
    "extra": [
      "советы трейн ксго2",
      "карта Train ксго2"
    ]
  },
  {
    "slug": "tips-train-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Train Counter-Strike 2",
    "extra": [
      "советы трейн Counter-Strike 2",
      "карта Train Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-train-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Train CS2",
    "extra": [
      "для новичков трейн CS2",
      "карта Train CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-train-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Train кс2",
    "extra": [
      "для новичков трейн кс2",
      "карта Train кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-train-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Train ксго2",
    "extra": [
      "для новичков трейн ксго2",
      "карта Train ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-train-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Train Counter-Strike 2",
    "extra": [
      "для новичков трейн Counter-Strike 2",
      "карта Train Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-italy-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Italy CS2",
    "extra": [
      "гайд италия CS2",
      "карта Italy CS2"
    ]
  },
  {
    "slug": "gayd-italy-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Italy кс2",
    "extra": [
      "гайд италия кс2",
      "карта Italy кс2"
    ]
  },
  {
    "slug": "gayd-italy-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Italy ксго2",
    "extra": [
      "гайд италия ксго2",
      "карта Italy ксго2"
    ]
  },
  {
    "slug": "gayd-italy-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Italy Counter-Strike 2",
    "extra": [
      "гайд италия Counter-Strike 2",
      "карта Italy Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-italy-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Italy CS2",
    "extra": [
      "тактика италия CS2",
      "карта Italy CS2"
    ]
  },
  {
    "slug": "taktika-italy-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Italy кс2",
    "extra": [
      "тактика италия кс2",
      "карта Italy кс2"
    ]
  },
  {
    "slug": "taktika-italy-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Italy ксго2",
    "extra": [
      "тактика италия ксго2",
      "карта Italy ксго2"
    ]
  },
  {
    "slug": "taktika-italy-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Italy Counter-Strike 2",
    "extra": [
      "тактика италия Counter-Strike 2",
      "карта Italy Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-italy-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Italy CS2",
    "extra": [
      "как играть италия CS2",
      "карта Italy CS2"
    ]
  },
  {
    "slug": "kak-igrat-italy-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Italy кс2",
    "extra": [
      "как играть италия кс2",
      "карта Italy кс2"
    ]
  },
  {
    "slug": "kak-igrat-italy-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Italy ксго2",
    "extra": [
      "как играть италия ксго2",
      "карта Italy ксго2"
    ]
  },
  {
    "slug": "kak-igrat-italy-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Italy Counter-Strike 2",
    "extra": [
      "как играть италия Counter-Strike 2",
      "карта Italy Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-italy-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Italy CS2",
    "extra": [
      "смоки италия CS2",
      "карта Italy CS2"
    ]
  },
  {
    "slug": "smoki-italy-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Italy кс2",
    "extra": [
      "смоки италия кс2",
      "карта Italy кс2"
    ]
  },
  {
    "slug": "smoki-italy-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Italy ксго2",
    "extra": [
      "смоки италия ксго2",
      "карта Italy ксго2"
    ]
  },
  {
    "slug": "smoki-italy-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Italy Counter-Strike 2",
    "extra": [
      "смоки италия Counter-Strike 2",
      "карта Italy Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-italy-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Italy CS2",
    "extra": [
      "позиции италия CS2",
      "карта Italy CS2"
    ]
  },
  {
    "slug": "pozicii-italy-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Italy кс2",
    "extra": [
      "позиции италия кс2",
      "карта Italy кс2"
    ]
  },
  {
    "slug": "pozicii-italy-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Italy ксго2",
    "extra": [
      "позиции италия ксго2",
      "карта Italy ксго2"
    ]
  },
  {
    "slug": "pozicii-italy-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Italy Counter-Strike 2",
    "extra": [
      "позиции италия Counter-Strike 2",
      "карта Italy Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-italy-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Italy CS2",
    "extra": [
      "коллауты италия CS2",
      "карта Italy CS2"
    ]
  },
  {
    "slug": "callouty-italy-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Italy кс2",
    "extra": [
      "коллауты италия кс2",
      "карта Italy кс2"
    ]
  },
  {
    "slug": "callouty-italy-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Italy ксго2",
    "extra": [
      "коллауты италия ксго2",
      "карта Italy ксго2"
    ]
  },
  {
    "slug": "callouty-italy-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Italy Counter-Strike 2",
    "extra": [
      "коллауты италия Counter-Strike 2",
      "карта Italy Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-italy-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Italy CS2",
    "extra": [
      "советы италия CS2",
      "карта Italy CS2"
    ]
  },
  {
    "slug": "tips-italy-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Italy кс2",
    "extra": [
      "советы италия кс2",
      "карта Italy кс2"
    ]
  },
  {
    "slug": "tips-italy-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Italy ксго2",
    "extra": [
      "советы италия ксго2",
      "карта Italy ксго2"
    ]
  },
  {
    "slug": "tips-italy-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Italy Counter-Strike 2",
    "extra": [
      "советы италия Counter-Strike 2",
      "карта Italy Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-italy-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Italy CS2",
    "extra": [
      "для новичков италия CS2",
      "карта Italy CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-italy-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Italy кс2",
    "extra": [
      "для новичков италия кс2",
      "карта Italy кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-italy-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Italy ксго2",
    "extra": [
      "для новичков италия ксго2",
      "карта Italy ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-italy-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Italy Counter-Strike 2",
    "extra": [
      "для новичков италия Counter-Strike 2",
      "карта Italy Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-office-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Office CS2",
    "extra": [
      "гайд офис CS2",
      "карта Office CS2"
    ]
  },
  {
    "slug": "gayd-office-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Office кс2",
    "extra": [
      "гайд офис кс2",
      "карта Office кс2"
    ]
  },
  {
    "slug": "gayd-office-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Office ксго2",
    "extra": [
      "гайд офис ксго2",
      "карта Office ксго2"
    ]
  },
  {
    "slug": "gayd-office-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Office Counter-Strike 2",
    "extra": [
      "гайд офис Counter-Strike 2",
      "карта Office Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-office-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Office CS2",
    "extra": [
      "тактика офис CS2",
      "карта Office CS2"
    ]
  },
  {
    "slug": "taktika-office-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Office кс2",
    "extra": [
      "тактика офис кс2",
      "карта Office кс2"
    ]
  },
  {
    "slug": "taktika-office-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Office ксго2",
    "extra": [
      "тактика офис ксго2",
      "карта Office ксго2"
    ]
  },
  {
    "slug": "taktika-office-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Office Counter-Strike 2",
    "extra": [
      "тактика офис Counter-Strike 2",
      "карта Office Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-office-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Office CS2",
    "extra": [
      "как играть офис CS2",
      "карта Office CS2"
    ]
  },
  {
    "slug": "kak-igrat-office-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Office кс2",
    "extra": [
      "как играть офис кс2",
      "карта Office кс2"
    ]
  },
  {
    "slug": "kak-igrat-office-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Office ксго2",
    "extra": [
      "как играть офис ксго2",
      "карта Office ксго2"
    ]
  },
  {
    "slug": "kak-igrat-office-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Office Counter-Strike 2",
    "extra": [
      "как играть офис Counter-Strike 2",
      "карта Office Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-office-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Office CS2",
    "extra": [
      "смоки офис CS2",
      "карта Office CS2"
    ]
  },
  {
    "slug": "smoki-office-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Office кс2",
    "extra": [
      "смоки офис кс2",
      "карта Office кс2"
    ]
  },
  {
    "slug": "smoki-office-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Office ксго2",
    "extra": [
      "смоки офис ксго2",
      "карта Office ксго2"
    ]
  },
  {
    "slug": "smoki-office-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Office Counter-Strike 2",
    "extra": [
      "смоки офис Counter-Strike 2",
      "карта Office Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-office-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Office CS2",
    "extra": [
      "позиции офис CS2",
      "карта Office CS2"
    ]
  },
  {
    "slug": "pozicii-office-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Office кс2",
    "extra": [
      "позиции офис кс2",
      "карта Office кс2"
    ]
  },
  {
    "slug": "pozicii-office-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Office ксго2",
    "extra": [
      "позиции офис ксго2",
      "карта Office ксго2"
    ]
  },
  {
    "slug": "pozicii-office-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Office Counter-Strike 2",
    "extra": [
      "позиции офис Counter-Strike 2",
      "карта Office Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-office-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Office CS2",
    "extra": [
      "коллауты офис CS2",
      "карта Office CS2"
    ]
  },
  {
    "slug": "callouty-office-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Office кс2",
    "extra": [
      "коллауты офис кс2",
      "карта Office кс2"
    ]
  },
  {
    "slug": "callouty-office-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Office ксго2",
    "extra": [
      "коллауты офис ксго2",
      "карта Office ксго2"
    ]
  },
  {
    "slug": "callouty-office-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Office Counter-Strike 2",
    "extra": [
      "коллауты офис Counter-Strike 2",
      "карта Office Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-office-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Office CS2",
    "extra": [
      "советы офис CS2",
      "карта Office CS2"
    ]
  },
  {
    "slug": "tips-office-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Office кс2",
    "extra": [
      "советы офис кс2",
      "карта Office кс2"
    ]
  },
  {
    "slug": "tips-office-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Office ксго2",
    "extra": [
      "советы офис ксго2",
      "карта Office ксго2"
    ]
  },
  {
    "slug": "tips-office-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Office Counter-Strike 2",
    "extra": [
      "советы офис Counter-Strike 2",
      "карта Office Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-office-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Office CS2",
    "extra": [
      "для новичков офис CS2",
      "карта Office CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-office-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Office кс2",
    "extra": [
      "для новичков офис кс2",
      "карта Office кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-office-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Office ксго2",
    "extra": [
      "для новичков офис ксго2",
      "карта Office ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-office-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Office Counter-Strike 2",
    "extra": [
      "для новичков офис Counter-Strike 2",
      "карта Office Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-agency-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Agency CS2",
    "extra": [
      "гайд эдженси CS2",
      "карта Agency CS2"
    ]
  },
  {
    "slug": "gayd-agency-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Agency кс2",
    "extra": [
      "гайд эдженси кс2",
      "карта Agency кс2"
    ]
  },
  {
    "slug": "gayd-agency-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Agency ксго2",
    "extra": [
      "гайд эдженси ксго2",
      "карта Agency ксго2"
    ]
  },
  {
    "slug": "gayd-agency-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "гайд Agency Counter-Strike 2",
    "extra": [
      "гайд эдженси Counter-Strike 2",
      "карта Agency Counter-Strike 2"
    ]
  },
  {
    "slug": "taktika-agency-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Agency CS2",
    "extra": [
      "тактика эдженси CS2",
      "карта Agency CS2"
    ]
  },
  {
    "slug": "taktika-agency-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Agency кс2",
    "extra": [
      "тактика эдженси кс2",
      "карта Agency кс2"
    ]
  },
  {
    "slug": "taktika-agency-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Agency ксго2",
    "extra": [
      "тактика эдженси ксго2",
      "карта Agency ксго2"
    ]
  },
  {
    "slug": "taktika-agency-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "тактика Agency Counter-Strike 2",
    "extra": [
      "тактика эдженси Counter-Strike 2",
      "карта Agency Counter-Strike 2"
    ]
  },
  {
    "slug": "kak-igrat-agency-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Agency CS2",
    "extra": [
      "как играть эдженси CS2",
      "карта Agency CS2"
    ]
  },
  {
    "slug": "kak-igrat-agency-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Agency кс2",
    "extra": [
      "как играть эдженси кс2",
      "карта Agency кс2"
    ]
  },
  {
    "slug": "kak-igrat-agency-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Agency ксго2",
    "extra": [
      "как играть эдженси ксго2",
      "карта Agency ксго2"
    ]
  },
  {
    "slug": "kak-igrat-agency-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "как играть Agency Counter-Strike 2",
    "extra": [
      "как играть эдженси Counter-Strike 2",
      "карта Agency Counter-Strike 2"
    ]
  },
  {
    "slug": "smoki-agency-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Agency CS2",
    "extra": [
      "смоки эдженси CS2",
      "карта Agency CS2"
    ]
  },
  {
    "slug": "smoki-agency-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Agency кс2",
    "extra": [
      "смоки эдженси кс2",
      "карта Agency кс2"
    ]
  },
  {
    "slug": "smoki-agency-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Agency ксго2",
    "extra": [
      "смоки эдженси ксго2",
      "карта Agency ксго2"
    ]
  },
  {
    "slug": "smoki-agency-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "смоки Agency Counter-Strike 2",
    "extra": [
      "смоки эдженси Counter-Strike 2",
      "карта Agency Counter-Strike 2"
    ]
  },
  {
    "slug": "pozicii-agency-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Agency CS2",
    "extra": [
      "позиции эдженси CS2",
      "карта Agency CS2"
    ]
  },
  {
    "slug": "pozicii-agency-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Agency кс2",
    "extra": [
      "позиции эдженси кс2",
      "карта Agency кс2"
    ]
  },
  {
    "slug": "pozicii-agency-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Agency ксго2",
    "extra": [
      "позиции эдженси ксго2",
      "карта Agency ксго2"
    ]
  },
  {
    "slug": "pozicii-agency-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "позиции Agency Counter-Strike 2",
    "extra": [
      "позиции эдженси Counter-Strike 2",
      "карта Agency Counter-Strike 2"
    ]
  },
  {
    "slug": "callouty-agency-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Agency CS2",
    "extra": [
      "коллауты эдженси CS2",
      "карта Agency CS2"
    ]
  },
  {
    "slug": "callouty-agency-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Agency кс2",
    "extra": [
      "коллауты эдженси кс2",
      "карта Agency кс2"
    ]
  },
  {
    "slug": "callouty-agency-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Agency ксго2",
    "extra": [
      "коллауты эдженси ксго2",
      "карта Agency ксго2"
    ]
  },
  {
    "slug": "callouty-agency-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "коллауты Agency Counter-Strike 2",
    "extra": [
      "коллауты эдженси Counter-Strike 2",
      "карта Agency Counter-Strike 2"
    ]
  },
  {
    "slug": "tips-agency-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Agency CS2",
    "extra": [
      "советы эдженси CS2",
      "карта Agency CS2"
    ]
  },
  {
    "slug": "tips-agency-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Agency кс2",
    "extra": [
      "советы эдженси кс2",
      "карта Agency кс2"
    ]
  },
  {
    "slug": "tips-agency-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Agency ксго2",
    "extra": [
      "советы эдженси ксго2",
      "карта Agency ксго2"
    ]
  },
  {
    "slug": "tips-agency-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "советы Agency Counter-Strike 2",
    "extra": [
      "советы эдженси Counter-Strike 2",
      "карта Agency Counter-Strike 2"
    ]
  },
  {
    "slug": "dlya-novichkov-agency-cs2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Agency CS2",
    "extra": [
      "для новичков эдженси CS2",
      "карта Agency CS2"
    ]
  },
  {
    "slug": "dlya-novichkov-agency-ks2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Agency кс2",
    "extra": [
      "для новичков эдженси кс2",
      "карта Agency кс2"
    ]
  },
  {
    "slug": "dlya-novichkov-agency-ksgo2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Agency ксго2",
    "extra": [
      "для новичков эдженси ксго2",
      "карта Agency ксго2"
    ]
  },
  {
    "slug": "dlya-novichkov-agency-counter-strike-2",
    "group": "cs2",
    "topic": "map",
    "kw": "для новичков Agency Counter-Strike 2",
    "extra": [
      "для новичков эдженси Counter-Strike 2",
      "карта Agency Counter-Strike 2"
    ]
  },
  {
    "slug": "gayd-ak47-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд AK-47 CS2",
    "extra": [
      "гайд ак 47 CS2"
    ]
  },
  {
    "slug": "gayd-ak47-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд AK-47 кс2",
    "extra": [
      "гайд ак 47 кс2"
    ]
  },
  {
    "slug": "gayd-ak47-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд AK-47 ксго2",
    "extra": [
      "гайд ак 47 ксго2"
    ]
  },
  {
    "slug": "kak-igrat-ak47-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть AK-47 CS2",
    "extra": [
      "как играть ак 47 CS2"
    ]
  },
  {
    "slug": "kak-igrat-ak47-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть AK-47 кс2",
    "extra": [
      "как играть ак 47 кс2"
    ]
  },
  {
    "slug": "kak-igrat-ak47-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть AK-47 ксго2",
    "extra": [
      "как играть ак 47 ксго2"
    ]
  },
  {
    "slug": "spray-ak47-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей AK-47 CS2",
    "extra": [
      "спрей ак 47 CS2"
    ]
  },
  {
    "slug": "spray-ak47-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей AK-47 кс2",
    "extra": [
      "спрей ак 47 кс2"
    ]
  },
  {
    "slug": "spray-ak47-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей AK-47 ксго2",
    "extra": [
      "спрей ак 47 ксго2"
    ]
  },
  {
    "slug": "rekoil-ak47-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача AK-47 CS2",
    "extra": [
      "отдача ак 47 CS2"
    ]
  },
  {
    "slug": "rekoil-ak47-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача AK-47 кс2",
    "extra": [
      "отдача ак 47 кс2"
    ]
  },
  {
    "slug": "rekoil-ak47-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача AK-47 ксго2",
    "extra": [
      "отдача ак 47 ксго2"
    ]
  },
  {
    "slug": "bay-ak47-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка AK-47 CS2",
    "extra": [
      "покупка ак 47 CS2"
    ]
  },
  {
    "slug": "bay-ak47-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка AK-47 кс2",
    "extra": [
      "покупка ак 47 кс2"
    ]
  },
  {
    "slug": "bay-ak47-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка AK-47 ксго2",
    "extra": [
      "покупка ак 47 ксго2"
    ]
  },
  {
    "slug": "sovety-ak47-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы AK-47 CS2",
    "extra": [
      "советы ак 47 CS2"
    ]
  },
  {
    "slug": "sovety-ak47-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы AK-47 кс2",
    "extra": [
      "советы ак 47 кс2"
    ]
  },
  {
    "slug": "sovety-ak47-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы AK-47 ксго2",
    "extra": [
      "советы ак 47 ксго2"
    ]
  },
  {
    "slug": "gayd-m4a1-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд M4A1-S CS2",
    "extra": [
      "гайд м4а1 CS2"
    ]
  },
  {
    "slug": "gayd-m4a1-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд M4A1-S кс2",
    "extra": [
      "гайд м4а1 кс2"
    ]
  },
  {
    "slug": "gayd-m4a1-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд M4A1-S ксго2",
    "extra": [
      "гайд м4а1 ксго2"
    ]
  },
  {
    "slug": "kak-igrat-m4a1-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть M4A1-S CS2",
    "extra": [
      "как играть м4а1 CS2"
    ]
  },
  {
    "slug": "kak-igrat-m4a1-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть M4A1-S кс2",
    "extra": [
      "как играть м4а1 кс2"
    ]
  },
  {
    "slug": "kak-igrat-m4a1-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть M4A1-S ксго2",
    "extra": [
      "как играть м4а1 ксго2"
    ]
  },
  {
    "slug": "spray-m4a1-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей M4A1-S CS2",
    "extra": [
      "спрей м4а1 CS2"
    ]
  },
  {
    "slug": "spray-m4a1-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей M4A1-S кс2",
    "extra": [
      "спрей м4а1 кс2"
    ]
  },
  {
    "slug": "spray-m4a1-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей M4A1-S ксго2",
    "extra": [
      "спрей м4а1 ксго2"
    ]
  },
  {
    "slug": "rekoil-m4a1-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача M4A1-S CS2",
    "extra": [
      "отдача м4а1 CS2"
    ]
  },
  {
    "slug": "rekoil-m4a1-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача M4A1-S кс2",
    "extra": [
      "отдача м4а1 кс2"
    ]
  },
  {
    "slug": "rekoil-m4a1-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача M4A1-S ксго2",
    "extra": [
      "отдача м4а1 ксго2"
    ]
  },
  {
    "slug": "bay-m4a1-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка M4A1-S CS2",
    "extra": [
      "покупка м4а1 CS2"
    ]
  },
  {
    "slug": "bay-m4a1-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка M4A1-S кс2",
    "extra": [
      "покупка м4а1 кс2"
    ]
  },
  {
    "slug": "bay-m4a1-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка M4A1-S ксго2",
    "extra": [
      "покупка м4а1 ксго2"
    ]
  },
  {
    "slug": "sovety-m4a1-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы M4A1-S CS2",
    "extra": [
      "советы м4а1 CS2"
    ]
  },
  {
    "slug": "sovety-m4a1-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы M4A1-S кс2",
    "extra": [
      "советы м4а1 кс2"
    ]
  },
  {
    "slug": "sovety-m4a1-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы M4A1-S ксго2",
    "extra": [
      "советы м4а1 ксго2"
    ]
  },
  {
    "slug": "gayd-m4a4-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд M4A4 CS2",
    "extra": [
      "гайд м4а4 CS2"
    ]
  },
  {
    "slug": "gayd-m4a4-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд M4A4 кс2",
    "extra": [
      "гайд м4а4 кс2"
    ]
  },
  {
    "slug": "gayd-m4a4-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд M4A4 ксго2",
    "extra": [
      "гайд м4а4 ксго2"
    ]
  },
  {
    "slug": "kak-igrat-m4a4-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть M4A4 CS2",
    "extra": [
      "как играть м4а4 CS2"
    ]
  },
  {
    "slug": "kak-igrat-m4a4-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть M4A4 кс2",
    "extra": [
      "как играть м4а4 кс2"
    ]
  },
  {
    "slug": "kak-igrat-m4a4-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть M4A4 ксго2",
    "extra": [
      "как играть м4а4 ксго2"
    ]
  },
  {
    "slug": "spray-m4a4-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей M4A4 CS2",
    "extra": [
      "спрей м4а4 CS2"
    ]
  },
  {
    "slug": "spray-m4a4-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей M4A4 кс2",
    "extra": [
      "спрей м4а4 кс2"
    ]
  },
  {
    "slug": "spray-m4a4-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей M4A4 ксго2",
    "extra": [
      "спрей м4а4 ксго2"
    ]
  },
  {
    "slug": "rekoil-m4a4-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача M4A4 CS2",
    "extra": [
      "отдача м4а4 CS2"
    ]
  },
  {
    "slug": "rekoil-m4a4-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача M4A4 кс2",
    "extra": [
      "отдача м4а4 кс2"
    ]
  },
  {
    "slug": "rekoil-m4a4-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача M4A4 ксго2",
    "extra": [
      "отдача м4а4 ксго2"
    ]
  },
  {
    "slug": "bay-m4a4-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка M4A4 CS2",
    "extra": [
      "покупка м4а4 CS2"
    ]
  },
  {
    "slug": "bay-m4a4-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка M4A4 кс2",
    "extra": [
      "покупка м4а4 кс2"
    ]
  },
  {
    "slug": "bay-m4a4-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка M4A4 ксго2",
    "extra": [
      "покупка м4а4 ксго2"
    ]
  },
  {
    "slug": "sovety-m4a4-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы M4A4 CS2",
    "extra": [
      "советы м4а4 CS2"
    ]
  },
  {
    "slug": "sovety-m4a4-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы M4A4 кс2",
    "extra": [
      "советы м4а4 кс2"
    ]
  },
  {
    "slug": "sovety-m4a4-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы M4A4 ксго2",
    "extra": [
      "советы м4а4 ксго2"
    ]
  },
  {
    "slug": "gayd-awp-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд AWP CS2",
    "extra": [
      "гайд авп CS2"
    ]
  },
  {
    "slug": "gayd-awp-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд AWP кс2",
    "extra": [
      "гайд авп кс2"
    ]
  },
  {
    "slug": "gayd-awp-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд AWP ксго2",
    "extra": [
      "гайд авп ксго2"
    ]
  },
  {
    "slug": "kak-igrat-awp-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть AWP CS2",
    "extra": [
      "как играть авп CS2"
    ]
  },
  {
    "slug": "kak-igrat-awp-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть AWP кс2",
    "extra": [
      "как играть авп кс2"
    ]
  },
  {
    "slug": "kak-igrat-awp-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть AWP ксго2",
    "extra": [
      "как играть авп ксго2"
    ]
  },
  {
    "slug": "spray-awp-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей AWP CS2",
    "extra": [
      "спрей авп CS2"
    ]
  },
  {
    "slug": "spray-awp-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей AWP кс2",
    "extra": [
      "спрей авп кс2"
    ]
  },
  {
    "slug": "spray-awp-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей AWP ксго2",
    "extra": [
      "спрей авп ксго2"
    ]
  },
  {
    "slug": "rekoil-awp-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача AWP CS2",
    "extra": [
      "отдача авп CS2"
    ]
  },
  {
    "slug": "rekoil-awp-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача AWP кс2",
    "extra": [
      "отдача авп кс2"
    ]
  },
  {
    "slug": "rekoil-awp-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача AWP ксго2",
    "extra": [
      "отдача авп ксго2"
    ]
  },
  {
    "slug": "bay-awp-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка AWP CS2",
    "extra": [
      "покупка авп CS2"
    ]
  },
  {
    "slug": "bay-awp-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка AWP кс2",
    "extra": [
      "покупка авп кс2"
    ]
  },
  {
    "slug": "bay-awp-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка AWP ксго2",
    "extra": [
      "покупка авп ксго2"
    ]
  },
  {
    "slug": "sovety-awp-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы AWP CS2",
    "extra": [
      "советы авп CS2"
    ]
  },
  {
    "slug": "sovety-awp-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы AWP кс2",
    "extra": [
      "советы авп кс2"
    ]
  },
  {
    "slug": "sovety-awp-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "советы AWP ксго2",
    "extra": [
      "советы авп ксго2"
    ]
  },
  {
    "slug": "gayd-deagle-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд Desert Eagle CS2",
    "extra": [
      "гайд дигл CS2"
    ]
  },
  {
    "slug": "gayd-deagle-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд Desert Eagle кс2",
    "extra": [
      "гайд дигл кс2"
    ]
  },
  {
    "slug": "gayd-deagle-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "гайд Desert Eagle ксго2",
    "extra": [
      "гайд дигл ксго2"
    ]
  },
  {
    "slug": "kak-igrat-deagle-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть Desert Eagle CS2",
    "extra": [
      "как играть дигл CS2"
    ]
  },
  {
    "slug": "kak-igrat-deagle-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть Desert Eagle кс2",
    "extra": [
      "как играть дигл кс2"
    ]
  },
  {
    "slug": "kak-igrat-deagle-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "как играть Desert Eagle ксго2",
    "extra": [
      "как играть дигл ксго2"
    ]
  },
  {
    "slug": "spray-deagle-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей Desert Eagle CS2",
    "extra": [
      "спрей дигл CS2"
    ]
  },
  {
    "slug": "spray-deagle-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей Desert Eagle кс2",
    "extra": [
      "спрей дигл кс2"
    ]
  },
  {
    "slug": "spray-deagle-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "спрей Desert Eagle ксго2",
    "extra": [
      "спрей дигл ксго2"
    ]
  },
  {
    "slug": "rekoil-deagle-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача Desert Eagle CS2",
    "extra": [
      "отдача дигл CS2"
    ]
  },
  {
    "slug": "rekoil-deagle-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача Desert Eagle кс2",
    "extra": [
      "отдача дигл кс2"
    ]
  },
  {
    "slug": "rekoil-deagle-ksgo2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "отдача Desert Eagle ксго2",
    "extra": [
      "отдача дигл ксго2"
    ]
  },
  {
    "slug": "bay-deagle-cs2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка Desert Eagle CS2",
    "extra": [
      "покупка дигл CS2"
    ]
  },
  {
    "slug": "bay-deagle-ks2",
    "group": "cs2",
    "topic": "weapon",
    "kw": "покупка Desert Eagle кс2",
    "extra": [
      "покупка дигл кс2"
    ]
  }
]
